# https://waha.devlike.pro/docs/how-to/install/
services:
  waha:
    restart: always
    image: devlikeapro/waha
    dns:
      - 1.1.1.1
      - 8.8.8.8

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

    ports:
      - '${WAHA_HOST_PORT:-3000}:3000'

    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

    env_file:
      - stack.env

volumes:
  waha_sessions:
    driver: local
  waha_media:
    driver: local
