# https://waha.devlike.pro/docs/how-to/install/
services:
  waha:
    restart: always
    image: devlikeapro/waha-plus
    dns:
      - 1.1.1.1
      - 8.8.8.8

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

    ports:
      - '${WAHA_HOST_PORT:-3000}:3000'

    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

    environment:
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME:-admin}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WHATSAPP_SWAGGER_USERNAME=${WHATSAPP_SWAGGER_USERNAME:-admin}
      - WHATSAPP_SWAGGER_PASSWORD=${WHATSAPP_SWAGGER_PASSWORD}
      - WAHA_DASHBOARD_ENABLED=True
      - WHATSAPP_SWAGGER_ENABLED=True
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_BASE_URL=http://localhost:3000
      - WAHA_LOG_FORMAT=JSON
      - WAHA_LOG_LEVEL=info
      - WAHA_PRINT_QR=False
      - WAHA_MEDIA_STORAGE=LOCAL
      - WHATSAPP_FILES_LIFETIME=0
      - TZ=${TZ:-America/Lima}

volumes:
  waha_sessions:
    driver: local
  waha_media:
    driver: local
